library(utils)
data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
subdata <- subset(data, data$Date == "1/2/2007" | data$Date == "2/2/2007")
GAP <- as.numeric(subdata$Global_active_power)
png("plot1.png")
hist(GAP, col = "red", xlab = "Global Active Power (kilowatts)", main = "Global Active Power")
dev.off()